In [4]:
# Linear Regression - Ordinary Least Squares
# 1. Line which has least Mean Squared Error ( only 1 which is best fit)

# Y = mx + c
# price = m*(sq ft) + intercept

# MSE - mean squared error
# Mean of Squared Differences between Actual and Estimation (Prediction)

# difficult 
# features: sqft, n of bedrooms, ladnmarks, children play area,  swmming pool, flooring
# output - price

# y = mx + c
# y = m1x1 + m2x2 + m4x4 + m6x6 + c




# -> write detailed formula




# prediction = W.X + b

# foreward propagation
# take data into model and get prediction


# back propagation(learning)
# calculate loss -> MSE
# adjust the weights such that MSE goes down

# optmization - gradient descent 
# code

# what are the weights set to?
# 1. weights are initialized randomly 
# as a part of training/learning, these weights need to be adjusted

# how did we get the best line?
# 1. adjusted weights.X + adjusted bias => best line

# jeoff hinton
# yann lecun




In [5]:
import pandas as pd
import numpy as np

In [6]:
data = pd.read_csv("california_housing_train.csv")

In [7]:
data.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  median_house_value  
0      1015.0       472.0         1.4936             66900.0  
1      1129.0       463.0         1.8200             80100.0  
2       333.0       117.0         1.6509             85700.0  
3       515.0       226.0         3.1917             73400.0  
4       624.0       262.0         1.9250             65500.0

In [8]:
data.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
dtype: int64

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB


In [10]:
# scale the data
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
data.iloc[:,:] = scaler.fit_transform(data)

In [11]:
data.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0   1.000000  0.175345            0.274510     0.147885        0.198945   
1   0.984064  0.197662            0.352941     0.201608        0.294848   
2   0.975100  0.122210            0.313725     0.018927        0.026847   
3   0.974104  0.116897            0.254902     0.039515        0.052142   
4   0.974104  0.109458            0.372549     0.038276        0.050435   

   population  households  median_income  median_house_value  
0    0.028364    0.077454       0.068530            0.107012  
1    0.031559    0.075974       0.091040            0.134228  
2    0.009249    0.019076       0.079378            0.145775  
3    0.014350    0.037000       0.185639            0.120414  
4    0.017405    0.042921       0.098281            0.104125

In [12]:
X = data.iloc[:, :-1].values # features
Y = data.iloc[:, -1].values # target/output

In [13]:
X.shape, Y.shape

((17000, 8), (17000,))

In [14]:
from sklearn.model_selection import train_test_split
Xtrain, Xtest, Ytrain, Ytest = train_test_split(X,Y, test_size = 0.2, shuffle = True, random_state = 4)

In [15]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(Xtrain, Ytrain)


LinearRegression()

In [16]:
#MSE
# mean of squared differences between actual and predictions

def MSE(actual, prediction):
  error = actual - prediction
  squared = np.square(error)
  return np.mean(squared)


In [17]:
prediction_testing = model.predict(Xtest)

MSE(Ytest, prediction_testing)

0.02000868218950632

In [18]:
model.coef_

array([-0.91447718, -0.84873666,  0.11771612, -0.66327286,  1.57499784,
       -2.68089479,  0.50641965,  1.20543441])

In [19]:
# rule
# a.b => columns of a should be equal to rows of b

def prediction(x, weights, b):
  return x.dot(weights) + b

In [20]:
Xtest.shape

(3400, 8)

In [21]:
prediction(Xtest, model.coef_, model.intercept_)

array([0.28914931, 0.44840173, 0.55358487, ..., 0.20538748, 0.52725745,
       0.75157992])

In [22]:
model.predict(Xtest)

array([0.28914931, 0.44840173, 0.55358487, ..., 0.20538748, 0.52725745,
       0.75157992])

In [23]:
# proves that our function give exact same result as that of sklearn algo

In [24]:
# Lasso and Ridge Regression



In [25]:
from sklearn.linear_model import Lasso, Ridge

model = Lasso()
model.fit(Xtrain,Ytrain)

Lasso()

Lasso()